name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - "mecab_python-*"
  pull_request:
    branches: [ "master" ]
jobs:
  build-python-lib:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x64
          - x86
        python:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: "Install Visual C++ for Python 2.7"
        if: matrix.python == '2.7'
        run: |
          choco install vcpython27 -f -y
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Setup Mecab-ko-msvc
        run: |
          curl -fSL -o 'mecab-ko-msvc-${{ matrix.arch }}.zip'  'https://github.com/Pusnow/mecab-ko-msvc/releases/download/release-0.9.2-msvc-3/mecab-ko-msvc-${{ matrix.arch }}.zip'
          7z x mecab-ko-msvc-${{ matrix.arch }}.zip -oc:\mecab
      - name: Prepare Python
        run: |
          pip install -U wheel
          pip install -U setuptools
      - name: Build Python Library
        run: .\build.cmd python setup.py bdist_wheel
      - name: Move whl files
        run: copy dist\*.whl .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "*.whl"
      - name: Release Artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.whl"
